### ISSUE TITLE
Chestshop tabcomplete issue in 1.13

### ISSUE THREAD

**Issue by LogGits** [ChestShop-authors/ChestShop-3#186]
In 1.13.2 these items show up in tab-complete list for users who dont have the permission to use them: `csGive, csVersion`.
this is because the plugin.yml is setup incorrectly to handle the command permissions. 
```yaml
  iteminfo:
    aliases: [iinfo]
    description: Lists item id and names
    usage: |
           /<command> §2(what's the item in hand?)
           /<command> §7log§f §2(what's the item ID of §7LOG§2?)
  csGive:
    description: Gives an item to the appropriate player
    usage: /<command> <item code> (amount) (player)
  csVersion:
    aliases: [chestshop]
    description: Shows the ChestShop's version
    usage: /<command>
  cstoggle:
    description: Toggle messages to the owner of a shop
    usage: /<command>
```
They need to have a `permission: ...` attribute.
With the same permission added to the `permissions:` section with `default: op`
