### ISSUE TITLE
Admins cannot buy in playershops

### ISSUE THREAD

**Issue by M1904** [ChestShop-authors/ChestShop-3#207]
[Please search for tickets with the same issues as yours first before reporting!]

#### Plugin Version
ChestShop version 3.9.3-SNAPSHOT (build 113)
 
#### Plugin Config
```yaml
TURN_OFF_UPDATES: false
#Do you want to turn off the automatic updates of ChestShop?

CACHE_SIZE: 1000
#How large should the internal uuid and name caches be?

SHOP_INTERACTION_INTERVAL: 100
#(In 1/1000th of a second) How often can a player use the shop sign?
IGNORE_CREATIVE_MODE: true
#Do you want to allow using shops to people in creative mode?
REVERSE_BUTTONS: false
#If true, people will buy with left-click and sell with right-click.
SHIFT_SELLS_IN_STACKS: false
#If true, people will be able to buy/sell in 64 stacks while holding the crouch button.
SHIFT_ALLOWS: "ALL"
#What can you do by clicking shift with SHIFT_SELLS_IN_STACKS turned on? (ALL/BUY/SELL)
ALLOW_SIGN_CHEST_OPEN: true
#Can shop's chest be opened by owner with right-clicking a shop's sign?
ALLOW_LEFT_CLICK_DESTROYING: true
#If true, when you left-click your own shop sign you won't open chest's inventory, but instead you will start destroying the sign.

REMOVE_EMPTY_SHOPS: false
#If true, if the shop is empty, the sign is destroyed and put into the chest, so the shop isn't usable anymore.
REMOVE_EMPTY_CHESTS: false
#If true, if the REMOVE_EMPTY_SHOPS option is turned on, the chest is also destroyed.

ADMIN_SHOP_NAME: "Adminshop"
#First line of your Admin Shop's sign should look like this:
SERVER_ECONOMY_ACCOUNT: ""
#The economy account which Admin Shops should use and to which all taxes will go
TAX_AMOUNT: 0
#Percent of the price that should go to the server's account. (100 = 100 percent)
SERVER_TAX_AMOUNT: 0
#Percent of the price that should go to the server's account when buying from an Admin Shop.
SHOP_CREATION_PRICE: 0.0
#Amount of money player must pay to create a shop
SHOP_REFUND_PRICE: 0.0
#How much money do you get back when destroying a sign?

BLOCK_SHOPS_WITH_SELL_PRICE_HIGHER_THAN_BUY_PRICE: true
#Should we block shops that sell things for more than they buy? (This prevents newbies from creating shops that would be exploited)

ALLOW_MULTIPLE_SHOPS_AT_ONE_BLOCK: false
#Do you want to allow other players to build a shop on a block where there's one already?
ALLOW_PARTIAL_TRANSACTIONS: true
#Can shops be used even when the seller doesn't have enough items? (The price will be scaled adequately to the item amount)
ALLOW_AUTO_ITEM_FILL: true
#Can '?' be put in place of item name in order for the sign to be auto-filled?

SHOW_MESSAGE_OUT_OF_STOCK: true
#Do you want to show "Out of stock" messages?
SHOW_MESSAGE_FULL_SHOP: true
#Do you want to show "Full shop" messages?

CSTOGGLE_TOGGLES_OUT_OF_STOCK: true
#Can players hide the "Out of stock" messages with /cstoggle?
CSTOGGLE_TOGGLES_FULL_SHOP: true
#Can players hide the "Full shop" messages with /cstoggle?
SHOW_TRANSACTION_INFORMATION_CLIENT: true
#Do you want to show "You bought/sold... " messages?
SHOW_TRANSACTION_INFORMATION_OWNER: true
#Do you want to show "Somebody bought/sold... " messages?

LOG_TO_FILE: true
#If true, plugin will log transactions in its own file
LOG_TO_CONSOLE: true
#Do you want ChestShop's messages to show up in console?

STACK_TO_64: false
#Do you want to stack all items up to 64 item stacks?
USE_BUILT_IN_PROTECTION: true
#Do you want to use built-in protection against chest destruction?
STICK_SIGNS_TO_CHESTS: false
#Do you want to have shop signs "stick" to chests?
TURN_OFF_DEFAULT_PROTECTION_WHEN_PROTECTED_EXTERNALLY: false
#EXPERIMENTAL: Do you want to turn off the default protection when another plugin is protecting the block? (Will leave the chest visually open - CraftBukkit bug!)
TURN_OFF_SIGN_PROTECTION: false
#Do you want to turn off the default sign protection? Warning! Other players will be able to destroy other people's shops!
TURN_OFF_HOPPER_PROTECTION: false
#Do you want to disable the hopper protection, which prevents the hoppers from taking items out of chests?
PROTECT_CHEST_WITH_LWC: false
#Do you want to protect shop chests with LWC?
PROTECT_SIGN_WITH_LWC: false
#Do you want to protect shop signs with LWC?
REMOVE_LWC_PROTECTION_AUTOMATICALLY: true
#Should the chest's LWC protection be removed once the shop sign is destroyed? 

WORLDGUARD_INTEGRATION: true
#Do you want to only let people build inside regions?
WORLDGUARD_USE_FLAG: true
#Do you want to only let people build inside region flagged by doing /region regionName flag allow-shop allow?
WORLDGUARD_USE_PROTECTION: true
#Do you want ChestShop to respect WorldGuard's chest protection?

AUTHME_HOOK: true
#Do you want to deny shop access to unlogged users?
AUTHME_ALLOW_UNREGISTERED: false
#Do you want to allow shop access to unregistered users? (Example: registration is optional)

HEROES_EXP: 100.0
#How much Heroes exp should people get for creating a ChestShop?

#A list of worlds in which to remove empty shops with the previous config. Case sensitive. An empty list means all worlds.
REMOVE_EMPTY_WORLDS: 
- "world1"
- "world2"
#How many decimal places are allowed at a maximum for prices?
PRICE_PRECISION: 2

#Add icons and make item names hoverable in transaction messages when ShowItem is installed?
SHOWITEM_MESSAGE: true


#What containers are allowed to hold a shop? (Only blocks with inventories work!)
SHOP_CONTAINERS: 
- "CHEST"
- "TRAPPED_CHEST"
#Do you want to allow using shops to people who have access to it due to their permissions? (owners are always ignored)
IGNORE_ACCESS_PERMS: false
```
 
#### Server Version
CraftBukkit version
git-Spigot-3cb9dcb-0f708cd (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
 
#### Server Log
[The full latest.log file]

#### What other plugins are you running?
ModernLWC version 2.1.2-dd8c289
WorldGuard version 7.0.0-SNAPSHOT;1795-72a392a
WolgGuardExtraFlags version 4.1.2
(and other 40 Plugins. Need all?)

#### What is happening?
I'm a Admin on a Server. I've got OP, I've got *-rights. I can create and destroy shops, shops in other names, create adminshop signs and so on. If I set the permission chestshop.admin to false, I cannot reload config-file or create Adminshop-signs. Perfect. But if I set the permission chestshop.mod to false, further i can destroy foreign shopsigns and create new in the name of others. I also cannot buy or sell with clicking by other shops, i always open the chest. That is really horrible! I have try it with AND without OP, logged new after changing. I have try it with "IGNORE_ACCESS_PERMS: false" AND "IGNORE_ACCESS_PERMS: true". Always the same result. What i have to change in my settings, that i can finally buy and sell with clicking the signs
