### ISSUE TITLE
Issue with ChestShop on Startup/Use

### ISSUE THREAD

**Issue by tubatyler** [ChestShop-authors/ChestShop-3#225]
[Please search for tickets with the same issues as yours first before reporting!]

#### Plugin Version
3.10-SNAPSHOT (Build 135)
 
#### Plugin Config
```yaml
#Do you want to turn off the automatic updates of ChestShop?
TURN_OFF_UPDATES: false

#How large should the internal caches be?
CACHE_SIZE: 1000

#What containers are allowed to hold a shop? (Only blocks with inventories work!)
SHOP_CONTAINERS: 
- "CHEST"
- "TRAPPED_CHEST"

#(In 1/1000th of a second) How often can a player use the shop sign?
SHOP_INTERACTION_INTERVAL: 250
#Do you want to allow using shops to people in creative mode?
IGNORE_CREATIVE_MODE: true
#Do you want to allow using shops to people who have access to it due to their permissions? (owners are always ignored)
IGNORE_ACCESS_PERMS: true
#If true, people will buy with left-click and sell with right-click.
REVERSE_BUTTONS: false
#If true, people will be able to buy/sell in 64 stacks while holding the crouch button.
SHIFT_SELLS_IN_STACKS: false
#What can you do by clicking shift with SHIFT_SELLS_IN_STACKS turned on? (ALL/BUY/SELL)
SHIFT_ALLOWS: "ALL"
#Can shop's chest be opened by owner with right-clicking a shop's sign?
ALLOW_SIGN_CHEST_OPEN: true
#If true, when you left-click your own shop sign you won't open chest's inventory, but instead you will start destroying the sign.
ALLOW_LEFT_CLICK_DESTROYING: true

#If true, if the shop is empty, the sign is destroyed and put into the chest, so the shop isn't usable anymore.
REMOVE_EMPTY_SHOPS: false
#If true, if the REMOVE_EMPTY_SHOPS option is turned on, the chest is also destroyed.
REMOVE_EMPTY_CHESTS: false
#A list of worlds in which to remove empty shops with the previous config. Case sensitive. An empty list means all worlds.
REMOVE_EMPTY_WORLDS: 
- "world1"
- "world2"

#First line of your Admin Shop's sign should look like this:
ADMIN_SHOP_NAME: "Admin Shop"
#The economy account which Admin Shops should use and to which all taxes will go
SERVER_ECONOMY_ACCOUNT: ""
#Percent of the price that should go to the server's account. (100 = 100 percent)
TAX_AMOUNT: 0
#Percent of the price that should go to the server's account when buying from an Admin Shop.
SERVER_TAX_AMOUNT: 0
#Amount of money player must pay to create a shop
SHOP_CREATION_PRICE: 0
#How much money do you get back when destroying a sign?
SHOP_REFUND_PRICE: 0
#How many decimal places are allowed at a maximum for prices?
PRICE_PRECISION: 2

#Should we block shops that sell things for more than they buy? (This prevents newbies from creating shops that would be exploited)
BLOCK_SHOPS_WITH_SELL_PRICE_HIGHER_THAN_BUY_PRICE: true

#Do you want to allow other players to build a shop on a block where there's one already?
ALLOW_MULTIPLE_SHOPS_AT_ONE_BLOCK: false
#Can shops be used even when the buyer/seller doesn't have enough items, space or money? (The price will be scaled adequately to the item amount)
ALLOW_PARTIAL_TRANSACTIONS: true
#Can '?' be put in place of item name in order for the sign to be auto-filled?
ALLOW_AUTO_ITEM_FILL: true

#Do you want to show "Out of stock" messages?
SHOW_MESSAGE_OUT_OF_STOCK: true
#Do you want to show "Full shop" messages?
SHOW_MESSAGE_FULL_SHOP: true

#Can players hide the "Out of stock" messages with /cstoggle?
CSTOGGLE_TOGGLES_OUT_OF_STOCK: false
#Can players hide the "Full shop" messages with /cstoggle?
CSTOGGLE_TOGGLES_FULL_SHOP: false
#Do you want to show "You bought/sold... " messages?
SHOW_TRANSACTION_INFORMATION_CLIENT: true
#Do you want to show "Somebody bought/sold... " messages?
SHOW_TRANSACTION_INFORMATION_OWNER: true

#If true, plugin will log transactions in its own file
LOG_TO_FILE: false
#Do you want ChestShop's messages to show up in console?
LOG_TO_CONSOLE: true
#Should all shop removals be logged to the console?
LOG_ALL_SHOP_REMOVALS: true

#Do you want to stack all items up to 64 item stacks?
STACK_TO_64: false
#Do you want to use built-in protection against chest destruction?
USE_BUILT_IN_PROTECTION: true
#Do you want to have shop signs "stick" to chests?
STICK_SIGNS_TO_CHESTS: false
#EXPERIMENTAL: Do you want to turn off the default protection when another plugin is protecting the block? (Will leave the chest visually open - CraftBukkit bug!)
TURN_OFF_DEFAULT_PROTECTION_WHEN_PROTECTED_EXTERNALLY: false
#Do you want to turn off the default sign protection? Warning! Other players will be able to destroy other people's shops!
TURN_OFF_SIGN_PROTECTION: false
#Do you want to disable the hopper protection, which prevents Hopper-Minecarts from taking items out of shops?
TURN_OFF_HOPPER_PROTECTION: false
#Do you want to protect shop chests with LWC?
PROTECT_CHEST_WITH_LWC: false
#Do you want to protect shop signs with LWC?
PROTECT_SIGN_WITH_LWC: false
#Should the chest's LWC protection be removed once the shop sign is destroyed? 
REMOVE_LWC_PROTECTION_AUTOMATICALLY: true

#Do you want to only let people build inside regions?
WORLDGUARD_INTEGRATION: false
#Do you want to only let people build inside region flagged by doing /region regionName flag allow-shop allow?
WORLDGUARD_USE_FLAG: false
#Do you want ChestShop to respect WorldGuard's chest protection?
WORLDGUARD_USE_PROTECTION: false

#Do you want to deny shop access to unlogged users?
AUTHME_HOOK: true
#Do you want to allow shop access to unregistered users? (Example: registration is optional)
AUTHME_ALLOW_UNREGISTERED: false

#How much Heroes exp should people get for creating a ChestShop?
HEROES_EXP: 100.0

#Add icons and make item names hoverable in transaction messages when ShowItem is installed?
SHOWITEM_MESSAGE: true
```
 
#### Server Version
https://gyazo.com/01ee7b04f09583d98627e0ef79d52a80

#### Server Log
[issue-225-server.log](https://gist.github.com/Phoenix616/f192201544e53e73eb6210a1e1fdb035)

#### What other plugins are you running?
CoreProtect, PlayerHeads, WorldEdit, WorldGuard, LampControl, AutoMessage, SetSpawn, RottenFlesh2Leather, MobHealthbars, PermissionsEx,BuyCraftX, Vault, Multiverse-Core, DiscordSRV, Essentials, AdvancedAchievements, ChatEx

#### What is happening?
This appeared on startup: https://pastebin.com/hGb0MZfN
This appeared when using /iteminfo: https://pastebin.com/uwqRHqwP
And when using /chestshop reload: https://pastebin.com/HR9Psnw1

#### What did you expect to happen?
I expected for the sign in proper formatting to work

Please provide any additional info below
