### ISSUE TITLE
REMOVE_EMPTY_SHOPS: true doesnt work

### ISSUE THREAD

**Issue by LordRazen** [ChestShop-authors/ChestShop-3#248]
#### Plugin Version
3.10-SNAPSHOT (build 149)
 
#### Plugin Config

```yaml
PREFERRED_ECONOMY_PLUGIN: ""
#(When not using Vault) Preferred economy plugin to use (iConomy/BOSEconomy/Essentials).

SHOP_INTERACTION_INTERVAL: 1000
#(In 1/1000th of a second) How often can a player use the shop sign?
IGNORE_CREATIVE_MODE: true
#Do you want to allow using shops to people in creative mode?
REVERSE_BUTTONS: false
#If true, people will buy with left-click and sell with right-click.
SHIFT_SELLS_IN_STACKS: false
#If true, people will be able to buy/sell in 64 stacks while holding the crouch button.
SHIFT_ALLOWS: "ALL"
#What can you do by clicking shift with SHIFT_SELLS_IN_STACKS turned on? (ALL/BUY/SELL)
ALLOW_SIGN_CHEST_OPEN: true
#Can shop's chest be opened by owner with right-clicking a shop's sign?
ALLOW_LEFT_CLICK_DESTROYING: true
#If true, when you left-click your own shop sign you won't open chest's inventory, but instead you will start destroying the sign.

REMOVE_EMPTY_SHOPS: true
#If true, if the shop is empty, the sign is destroyed and put into the chest, so the shop isn't usable anymore.
REMOVE_EMPTY_CHESTS: false
#If true, if the REMOVE_EMPTY_SHOPS option is turned on, the chest is also destroyed.

ADMIN_SHOP_NAME: "Admin Shop"
#First line of your Admin Shop's sign should look like this:
SERVER_ECONOMY_ACCOUNT: ""
#The economy account which Admin Shops should use and to which all taxes will go
BANK_MEMBERS_ALLOWED: true
#Whether bank account members (if available) can create shops on its behalf
TAX_AMOUNT: 0
#Percent of the price that should go to the server's account. (100 = 100 percent)
BANK_TAX_AMOUNT: 0
#Percent of the price that should go to the server's account when buying from a bank.
SERVER_TAX_AMOUNT: 0
#Percent of the price that should go to the server's account when buying from an Admin Shop.
SHOP_CREATION_PRICE: 0.0
#Amount of money player must pay to create a shop
SHOP_REFUND_PRICE: 0.0
#How much money do you get back when destroying a sign?

BLOCK_SHOPS_WITH_SELL_PRICE_HIGHER_THAN_BUY_PRICE: true
#Should we block shops that sell things for more than they buy? (This prevents newbies from creating shops that would be exploited)

ALLOW_MULTIPLE_SHOPS_AT_ONE_BLOCK: false
#Do you want to allow other players to build a shop on a block where there's one already?
ALLOW_PARTIAL_TRANSACTIONS: true
#Can shops be used even when the seller doesn't have enough items? (The price will be scaled adequatly to the item amount)

SHOW_MESSAGE_OUT_OF_STOCK: true
#Do you want to show "Out of stock" messages?
SHOW_TRANSACTION_INFORMATION_CLIENT: true
#Do you want to show "You bought/sold... " messages?
SHOW_TRANSACTION_INFORMATION_OWNER: true
#Do you want to show "Somebody bought/sold... " messages?

LOG_TO_FILE: true
#If true, plugin will log transactions in its own file
LOG_TO_CONSOLE: false
#Do you want ChestShop's messages to show up in console?
LOG_TO_DATABASE: false
#If true, plugin will log transactions in EBean database
RECORD_TIME_TO_LIVE: 600
#How long should transaction information be stored in the database (in seconds, -1 means forever)?

STACK_TO_64: false
#Do you want to stack all items up to 64 item stacks?
USE_BUILT_IN_PROTECTION: true
#Do you want to use built-in protection against chest destruction?
STICK_SIGNS_TO_CHESTS: false
#Do you want to have shop signs "stick" to chests?
TURN_OFF_DEFAULT_PROTECTION_WHEN_PROTECTED_EXTERNALLY: false
#EXPERIMENTAL: Do you want to turn off the default protection when another plugin is protecting the block? (Will leave the chest visually open - CraftBukkit bug!)
TURN_OFF_SIGN_PROTECTION: false
#Do you want to turn off the default sign protection? Warning! Other players will be able to destroy other people's shops!
TURN_OFF_HOPPER_PROTECTION: false
#Do you want to disable the hopper protection, which prevents the hoppers from taking items out of chests?
PROTECT_CHEST_WITH_LWC: false
#Do you want to protect shop chests with LWC?
PROTECT_SIGN_WITH_LWC: false
#Do you want to protect shop signs with LWC?

GENERATE_STATISTICS_PAGE: false
#If true, plugin will generate shop statistics webpage.
STATISTICS_PAGE_PATH: "plugins/ChestShop/website.html"
#Where should your generated website be saved?
STATISTICS_PAGE_GENERATION_INTERVAL: 60
#How often should the website be generated?

WORLDGUARD_INTEGRATION: false
#Do you want to only let people build inside regions?
WORLDGUARD_USE_FLAG: true
#Do you want to only let poeple build inside region flagged by doing /region regionName flag chestshop allow?
WORLDGUARD_USE_PROTECTION: false
#Do you want ChestShop to respect WorldGuard's chest protection?

HEROES_EXP: 100.0
#How much Heroes exp should people get for creating a ChestShop?

TURN_OFF_UPDATES: false
#Do you want to turn off the automatic updates of ChestShop?
ALLOW_AUTO_ITEM_FILL: true
#Can '?' be put in place of item name in order for the sign to be auto-filled?

REMOVE_LWC_PROTECTION_AUTOMATICALLY: true
#Should the chest's LWC protection be removed once the shop sign is destroyed? 


#How large should the internal caches be?
CACHE_SIZE: 1000

#What containers are allowed to hold a shop? (Only blocks with inventories work!)
SHOP_CONTAINERS: 
- "CHEST"
- "TRAPPED_CHEST"
#Do you want to allow using shops to people who have access to it due to their permissions? (owners are always ignored)
IGNORE_ACCESS_PERMS: true
#A list of worlds in which to remove empty shops with the previous config. Case sensitive. An empty list means all worlds.
REMOVE_EMPTY_WORLDS: 
- "world1"
- "world2"
#How many decimal places are allowed at a maximum for prices?
PRICE_PRECISION: 2
#Do you want to show "Full shop" messages?
SHOW_MESSAGE_FULL_SHOP: true

#Can players hide the "Out of stock" messages with /cstoggle?
CSTOGGLE_TOGGLES_OUT_OF_STOCK: false
#Can players hide the "Full shop" messages with /cstoggle?
CSTOGGLE_TOGGLES_FULL_SHOP: false

#Do you want to deny shop access to unlogged users?
AUTHME_HOOK: true
#Do you want to allow shop access to unregistered users? (Example: registration is optional)
AUTHME_ALLOW_UNREGISTERED: false

#Add icons and make item names hoverable in transaction messages when ShowItem is installed?
SHOWITEM_MESSAGE: true

#How many seconds do you want to wait before showing notifications for the same shop to the owner again?
NOTIFICATION_MESSAGE_COOLDOWN: 10
#Should all shop removals be logged to the console?
LOG_ALL_SHOP_REMOVALS: true
```
 
#### Server Version
Paper version git-Paper-629 (MC:1.13.2)
 
#### Server Log
Those are all messages from the log concerning Chestshop - there're no Stacktraces or so

> Line 58: [20:29:29] [Server thread/INFO]: [ChestShop] Loading ChestShop v3.10-SNAPSHOT (build 149)
> Line 58: [20:29:29] [Server thread/INFO]: [ChestShop] Loading ChestShop v3.10-SNAPSHOT (build 149)
> Line 59: [20:29:29] [Server thread/INFO]: [ChestShop] LWC version 2.1.2-dd8c289 loaded.
> Line 60: [20:29:29] [Server thread/INFO]: [ChestShop] WorldGuard version 7.0.0-SNAPSHOT;1910-b152cdc loaded.
> Line 61: [20:29:29] [Server thread/INFO]: [ChestShopNotifier] Loading ChestShopNotifier v1.3.0-SNAPSHOT (build #36)
> Line 61: [20:29:29] [Server thread/INFO]: [ChestShopNotifier] Loading ChestShopNotifier v1.3.0-SNAPSHOT (build #36)
> Line 610: [20:29:39] [Server thread/INFO]: [ChestShop] Enabling ChestShop v3.10-SNAPSHOT (build 149)
> Line 610: [20:29:39] [Server thread/INFO]: [ChestShop] Enabling ChestShop v3.10-SNAPSHOT (build 149)
> Line 611: [20:29:39] [Server thread/INFO]: [ChestShop] LWC version 2.1.2-dd8c289 loaded.
> Line 612: [20:29:39] [Server thread/INFO]: [ChestShop] Using Craftconomy3 as the Economy provider now.
> Line 613: [20:29:39] [Server thread/INFO]: [ChestShop] Vault loaded!
> Line 614: [20:29:39] [Server thread/WARN]: [ChestShop] Could not convert numeric IDs in priceLimits.yml to Material names!
> Line 615: [20:29:39] [Server thread/WARN]: [ChestShop] If you want to automatically convert them you have to run this version on a pre 1.13 server.
> Line 616: [20:29:39] [Server thread/WARN]: [ChestShop] If you want to manually convert it and hide this message set the uses_materials key to true.
> Line 617: [20:29:39] [Server thread/INFO]: [ChestShopNotifier] Enabling ChestShopNotifier v1.3.0-SNAPSHOT (build #36)*
> Line 617: [20:29:39] [Server thread/INFO]: [ChestShopNotifier] Enabling ChestShopNotifier v1.3.0-SNAPSHOT (build #36)*
> Line 618: [20:29:39] [Server thread/INFO]: [ChestShopNotifier] Connecting to the database...
> Line 634: [20:29:41] [Craft Scheduler Thread - 11/INFO]: [ChestShopNotifier] Database connected!
> Line 761: [20:46:10] [Server thread/INFO]: LordRazen issued server command: /version ChestShop

#### What other plugins are you running?
Craftconomy3
Vault
We tested the problem on a server stripped down to as less plugins as possible and it still appear, so the plugins on the liveserver are not important

#### What is happening?
Simple: With "REMOVE_EMPTY_SHOPS: true" in the config and a buyer who buys everything from your shop, the shopsign is not removed.

#### What did you expect to happen?
erm... just buying...
