### ISSUE TITLE
I want to set pricelimits for some items

### ISSUE THREAD

**Issue by felipeleite5w** [ChestShop-authors/ChestShop-3#279]
Hi, I wanna set pricelimits for some items 

I did with an item and it worked however i dont know how to do with multiple items... 

Could anyone help me? 
The IDS are 4404 , 4403 , 4402 , 4401
Chestshop version 3.7.6

# In this file you can configure maximum and minimum prices for items (when creating a shop).
max:
  buy_price:
    itemID: 4403
    '4403': 2
    sell_price:
    '4403': 2
min:
  buy_price:
    '4403': 1
  sell_price:
    '4403': 1

I know its a weird price, dont ask me why .-.

**Comment by Phoenix616** [comment]
Could you please fix your config, either by using the code formatting or a gist? Otherwise it's hard to see what might be the issue in your config.

Also please note that running such an old version might result in some changes/fixes not being available to you if there happens to be a bug with this.

**Comment by felipeleite5w** [comment]
> Could you please fix your config, either by using the code formatting or a gist? Otherwise it's hard to see what might be the issue in your config.
> 
> Also please note that running such an old version might result in some changes/fixes not being available to you if there happens to be a bug with this.

https://gist.github.com/felipeleite5w/73e7592f0d358a8ae655388bea846541

**Comment by Phoenix616** [comment]
Your config isn't indented correctly, line 6 needs to be on the same level as line 3. (Also line 4 isn't necessary afaik)

**Comment by felipeleite5w** [comment]
Ok, im not good in ChestShop, so could you help me fixing the Pricelimits ?

**Comment by felipeleite5w** [comment]
The IDS are 4404 , 4403 , 4402 , 4401 @Phoenix616   

And thanks for ChestShop, its an amazing plugin

**Comment by felipeleite5w** [comment]
@Phoenix616 are u there?

**Comment by Phoenix616** [comment]
Just use the correct syntax as explained in the default config?

Something like this should work:
```yaml
# In this file you can configure maximum and minimum prices for items (when creating a shop).
max:
  buy_price:
    '4403': 0.2
  sell_price:
    '4403': 0.2
min:
  buy_price:
    '4403': 0.01
  sell_price:
    '4403': 0.1
```
You should really learn how to intend yaml properly if you intend to run a server...
