### ISSUE TITLE
Startup and chestshop interaction errors (database related?)

### ISSUE THREAD

**Issue by mrcoffee1026** [ChestShop-authors/ChestShop-3#446]
#### Plugin Version

 [18:44:24 INFO]: ChestShop version 3.12-SNAPSHOT (build 293)
[18:44:24 INFO]: A chest shop for economy plugins.
[18:44:24 INFO]: Authors: Acrobot and https://github.com/ChestShop-authors/ChestShop-3/contributors

 
#### Plugin Config

<details>
  <summary>Config</summary>
  
 ```yaml
TURN_OFF_UPDATES: false
#Do you want to turn off the automatic updates of ChestShop?

CACHE_SIZE: 1000
#How large should the internal uuid and name caches be?

SHOP_INTERACTION_INTERVAL: 750
#(In 1/1000th of a second) How often can a player use the shop sign?
IGNORE_CREATIVE_MODE: true
#Do you want to allow using shops to people in creative mode?
REVERSE_BUTTONS: false
#If true, people will buy with left-click and sell with right-click.
SHIFT_SELLS_IN_STACKS: true
#If true, people will be able to buy/sell in 64 stacks while holding the crouch button.
SHIFT_ALLOWS: "SELL"
#What can you do by clicking shift with SHIFT_SELLS_IN_STACKS turned on? (ALL/BUY/SELL)
ALLOW_SIGN_CHEST_OPEN: true
#Can shop's chest be opened by owner with right-clicking a shop's sign?
ALLOW_LEFT_CLICK_DESTROYING: true
#If true, when you left-click your own shop sign you won't open chest's inventory, but instead you will start destroying the sign.

REMOVE_EMPTY_SHOPS: false
#If true, if the shop is empty, the sign is destroyed and put into the chest, so the shop isn't usable anymore.
REMOVE_EMPTY_CHESTS: false
#If true, if the REMOVE_EMPTY_SHOPS option is turned on, the chest is also destroyed.

ADMIN_SHOP_NAME: "Admin Shop"
#First line of your Admin Shop's sign should look like this:
SERVER_ECONOMY_ACCOUNT: ""
#The economy account which Admin Shops should use and to which all taxes will go
TAX_AMOUNT: 0
#Percent of the price that should go to the server's account. (100 = 100 percent)
SERVER_TAX_AMOUNT: 0
#Percent of the price that should go to the server's account when buying from an Admin Shop.
SHOP_CREATION_PRICE: 0.0
#Amount of money player must pay to create a shop
SHOP_REFUND_PRICE: 0.0
#How much money do you get back when destroying a sign?

BLOCK_SHOPS_WITH_SELL_PRICE_HIGHER_THAN_BUY_PRICE: true
#Should we block shops that sell things for more than they buy? (This prevents newbies from creating shops that would be exploited)

ALLOW_MULTIPLE_SHOPS_AT_ONE_BLOCK: false
#Do you want to allow other players to build a shop on a block where there's one already?
ALLOW_PARTIAL_TRANSACTIONS: true
#Can shops be used even when the seller doesn't have enough items? (The price will be scaled adequately to the item amount)
ALLOW_AUTO_ITEM_FILL: true
#Can '?' be put in place of item name in order for the sign to be auto-filled?

SHOW_MESSAGE_OUT_OF_STOCK: true
#Do you want to show "Out of stock" messages?
SHOW_MESSAGE_FULL_SHOP: true
#Do you want to show "Full shop" messages?

CSTOGGLE_TOGGLES_OUT_OF_STOCK: false
#Can players hide the "Out of stock" messages with /cstoggle?
CSTOGGLE_TOGGLES_FULL_SHOP: false
#Can players hide the "Full shop" messages with /cstoggle?
SHOW_TRANSACTION_INFORMATION_CLIENT: true
#Do you want to show "You bought/sold... " messages?
SHOW_TRANSACTION_INFORMATION_OWNER: true
#Do you want to show "Somebody bought/sold... " messages?

LOG_TO_FILE: true
#If true, plugin will log transactions in its own file
LOG_TO_CONSOLE: false
#Do you want ChestShop's messages to show up in console?

STACK_TO_64: false
#Do you want to stack all items up to 64 item stacks?
USE_BUILT_IN_PROTECTION: true
#Do you want to use built-in protection against chest destruction?
STICK_SIGNS_TO_CHESTS: true
#Do you want to have shop signs "stick" to chests?
TURN_OFF_DEFAULT_PROTECTION_WHEN_PROTECTED_EXTERNALLY: false
#EXPERIMENTAL: Do you want to turn off the default protection when another plugin is protecting the block? (Will leave the chest visually open - CraftBukkit bug!)
TURN_OFF_SIGN_PROTECTION: false
#Do you want to turn off the default sign protection? Warning! Other players will be able to destroy other people's shops!
TURN_OFF_HOPPER_PROTECTION: true
#Do you want to disable the hopper protection, which prevents the hoppers from taking items out of chests?
PROTECT_CHEST_WITH_LWC: true
#Do you want to protect shop chests with LWC?
PROTECT_SIGN_WITH_LWC: true
#Do you want to protect shop signs with LWC?
REMOVE_LWC_PROTECTION_AUTOMATICALLY: true
#Should the chest's LWC protection be removed once the shop sign is destroyed? 

WORLDGUARD_INTEGRATION: false
#Do you want to only let people build inside regions?
WORLDGUARD_USE_FLAG: true
#Do you want to only let poeple build inside region flagged by doing /region regionName flag chestshop allow?
WORLDGUARD_USE_PROTECTION: true
#Do you want ChestShop to respect WorldGuard's chest protection?

AUTHME_HOOK: false
#Do you want to deny shop access to unlogged users?
AUTHME_ALLOW_UNREGISTERED: false
#Do you want to allow shop access to unregistered users? (Example: registration is optional)

HEROES_EXP: 0.0
#How much Heroes exp should people get for creating a ChestShop?

#A list of worlds in which to remove empty shops with the previous config. Case sensitive. An empty list means all worlds.
REMOVE_EMPTY_WORLDS: 
- "world1"
- "world2"

#Add icons and make item names hoverable in transaction messages when ShowItem is installed?
SHOWITEM_MESSAGE: true


#What containers are allowed to hold a shop? (Only blocks with inventories work!)
SHOP_CONTAINERS: 
- "CHEST"
- "TRAPPED_CHEST"
#Do you want to allow using shops to people who have access to it due to their permissions? (owners are always ignored)
IGNORE_ACCESS_PERMS: true
#How many decimal places are allowed at a maximum for prices?
PRICE_PRECISION: 2
#Should all shop removals be logged to the console?
LOG_ALL_SHOP_REMOVALS: true

#How many seconds do you want to wait before showing notifications for the same shop to the owner again?
NOTIFICATION_MESSAGE_COOLDOWN: 10


#Enable this if you use BungeeCord and want players to receive shop notifications on other servers
BUNGEECORD_MESSAGES: false

# Should the plugin log some messages that are useful for debugging?
DEBUG: false
# Do you want to turn off the automatic notifications for new development builds?
TURN_OFF_DEV_UPDATE_NOTIFIER: false
# Do you want to include some values of this config in the metrics? (This will not leak sensitive data but help in the development process)
INCLUDE_SETTINGS_IN_METRICS: true

# The default language when the client's language can't be found.
DEFAULT_LANGUAGE: "en"
# Should the plugin try to use a language file that matches the client's locale setting?
USE_CLIENT_LOCALE: true
# If true, people will be able to sell/buy everything available of the same type.
SHIFT_SELLS_EVERYTHING: false
# Make all admin shops be unlimited even if they have a shop container at the sign
FORCE_UNLIMITED_ADMIN_SHOP: true
# The uuid of the economy account for the Admin Shop. Useful for fake accounts as normally only accounts of players work
SERVER_ECONOMY_ACCOUNT_UUID: 00000000-0000-0000-0000-000000000000
# This makes sure that the UUIDs of player shop accounts match the server's online-mode setting. Disabling this might lead to issues with offline players and is therefore unsupported!
ENSURE_CORRECT_PLAYERID: true
# This regexp validates the name of the player. If the name doesn't match, the player will neither be able to create a valid shop sign, nor buy/sell from a shop.
# Note for Bedrock support: If you have Floodgate on your server, you should set this regexp to ^\\*?\\w+$ and ENSURE_CORRECT_PLAYERID to false
# If your Floodgate prefix is not *, change the first * in the regexp (the one before the question mark) to whatever your prefix is.
VALID_PLAYERNAME_REGEXP: "^\\w+$"

# Maximum amount of items that can be bought/sold at a shop. Default 3456 is a double chest of 64 stacks.
MAX_SHOP_AMOUNT: 3456
# Only allow users to buy/sell that have access to the sign's protection? (E.g. LWC protection)
CHECK_ACCESS_FOR_SHOP_USE: false
# Of which type should the container protection be? Possible type: public, private, donate and on some LWC versions display
LWC_CHEST_PROTECTION_TYPE: "PRIVATE"
# Of which type should the sign protection be? Possible type: public, private, donate and on some LWC versions display
LWC_SIGN_PROTECTION_TYPE: "PRIVATE"
# Should LWC limits block shop creations?
LWC_LIMITS_BLOCK_CREATION: true

# Do you want to only let people build inside GriefPrevention claims?
GRIEFPREVENTION_INTEGRATION: false

# Do you want to only let people build inside RedProtect regions?
REDPROTECT_INTEGRATION: false

# Add stock counter to quantity line?
USE_STOCK_COUNTER: false

 ```
 
 </details>
 
#### Server Version

 [18:45:19 INFO]: This server is running Paper version git-Paper-683 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 20 version(s) behind

 
#### Server Log

<details>
  <summary>Log</summary>

```
chestshop latest.log on startup: https://pastebin.com/7B8GAT59
chestshop on player interaction: https://pastebin.com/bAjcRrVS
```

</details>

#### What other plugins are you running?

Many, but that's not relevant for this issue.

#### What is happening?

Startup errors related to the database files, additional errors when chest shops are used.

#### What did you expect to happen?

Ideally: no errors.
