### ISSUE TITLE
Customize the shops Buy (B) and Sell (S) identifier

### ISSUE THREAD

**Issue by Over2Craft-mc** [ChestShop-authors/ChestShop-3#449]
I would like to be able to have different and translated value for the **B**uy and **S**ell identifier on the third line of a Shop : 
- A short identifier 
- A long identifier

Here is an example of a configuration implementation that could handle this 
```YML
identifier:

  # This option would be used to customize the identifier which is actually "S" IF there is only a sell price (to avoid line OverFlow)
  long_sell:
  - "Vente" # which mean "sell" in french

  # This option would be used to customize the identifier which is actually "S" IF the shop also have a buy price
  short_sell:
  - "V" # The first value of this list would be use by default
  - "S" # We can provide on other value to avoid breaking older shops
 
  long_buy:
  - "Achat" # which mean "buy" in french
 
  short_buy:
  - "A"
  - "B"

```

Short and long notation could support colors which could be pretty nice for players to check if it's a sell or buy shop with a quick look

![image](https://user-images.githubusercontent.com/74878280/120063720-d48bde00-c068-11eb-8916-57f685c0fe0e.png)
