### ISSUE TITLE
Shops not being able to be properly created by Geyser players (With a + prefix)

### ISSUE THREAD

**Issue by USBCharger** [ChestShop-authors/ChestShop-3#495]
### What is happening?

When I create a chestshop on my bedrock account +Rockethub it tells me the shop was successfully created, yet when I interact with it, nothing happens, and when I do /chestshop no shop comes up.

The only line that came up in console is this:
[04:35:14 INFO]: [ChestShop] +Rockethub created a shop - 1 Stone - B 1 - at [world] 6426, 90, -6101****

https://imgur.com/a/lzzW7jX

### What did you expect to happen?

^^^ Stated above ^^^

### Plugin Version

3.12.1-SNAPSHOT

### Plugin Config

<details>
  <summary>Config</summary>

 ```yaml
#Do you want to turn off the automatic updates of ChestShop?
TURN_OFF_UPDATES: false

#How large should the internal caches be?
CACHE_SIZE: 1000

#What containers are allowed to hold a shop? (Only blocks with inventories work!)
SHOP_CONTAINERS: 
- "CHEST"
- "TRAPPED_CHEST"
- "BARREL"

#(In 1/1000th of a second) How often can a player use the shop sign?
SHOP_INTERACTION_INTERVAL: 250
#Do you want to allow using shops to people in creative mode?
IGNORE_CREATIVE_MODE: true
#Do you want to allow using shops to people who have access to it due to their permissions? (owners are always ignored)
IGNORE_ACCESS_PERMS: true
#If true, people will buy with left-click and sell with right-click.
REVERSE_BUTTONS: false
#If true, people will be able to buy/sell in 64 stacks while holding the crouch button.
SHIFT_SELLS_IN_STACKS: false
#What can you do by clicking shift with SHIFT_SELLS_IN_STACKS turned on? (ALL/BUY/SELL)
SHIFT_ALLOWS: "ALL"
#Can shop's chest be opened by owner with right-clicking a shop's sign?
ALLOW_SIGN_CHEST_OPEN: true
#If true, when you left-click your own shop sign you won't open chest's inventory, but instead you will start destroying the sign.
ALLOW_LEFT_CLICK_DESTROYING: true

#If true, if the shop is empty, the sign is destroyed and put into the chest, so the shop isn't usable anymore.
REMOVE_EMPTY_SHOPS: false
#If true, if the REMOVE_EMPTY_SHOPS option is turned on, the chest is also destroyed.
REMOVE_EMPTY_CHESTS: false
#A list of worlds in which to remove empty shops with the previous config. Case sensitive. An empty list means all worlds.
REMOVE_EMPTY_WORLDS: 
- "world1"
- "world2"

#First line of your Admin Shop's sign should look like this:
ADMIN_SHOP_NAME: "Admin Shop"
#The economy account which Admin Shops should use and to which all taxes will go
SERVER_ECONOMY_ACCOUNT: ""
#Percent of the price that should go to the server's account. (100 = 100 percent)
TAX_AMOUNT: 0
#Percent of the price that should go to the server's account when buying from an Admin Shop.
SERVER_TAX_AMOUNT: 0
#Amount of money player must pay to create a shop
SHOP_CREATION_PRICE: 0
#How much money do you get back when destroying a sign?
SHOP_REFUND_PRICE: 0
#How many decimal places are allowed at a maximum for prices?
PRICE_PRECISION: 2

#Should we block shops that sell things for more than they buy? (This prevents newbies from creating shops that would be exploited)
BLOCK_SHOPS_WITH_SELL_PRICE_HIGHER_THAN_BUY_PRICE: true

#Do you want to allow other players to build a shop on a block where there's one already?
ALLOW_MULTIPLE_SHOPS_AT_ONE_BLOCK: true
#Can shops be used even when the buyer/seller doesn't have enough items, space or money? (The price will be scaled adequately to the item amount)
ALLOW_PARTIAL_TRANSACTIONS: true
#Can '?' be put in place of item name in order for the sign to be auto-filled?
ALLOW_AUTO_ITEM_FILL: true

#Enable this if you use BungeeCord and want players to receive shop notifications on other servers
BUNGEECORD_MESSAGES: false

#Do you want to show "Out of stock" messages?
SHOW_MESSAGE_OUT_OF_STOCK: true
#Do you want to show "Full shop" messages?
SHOW_MESSAGE_FULL_SHOP: true
#How many seconds do you want to wait before showing notifications for the same shop to the owner again?
NOTIFICATION_MESSAGE_COOLDOWN: 10

#Can players hide the "Out of stock" messages with /cstoggle?
CSTOGGLE_TOGGLES_OUT_OF_STOCK: false
#Can players hide the "Full shop" messages with /cstoggle?
CSTOGGLE_TOGGLES_FULL_SHOP: false
#Do you want to show "You bought/sold... " messages?
SHOW_TRANSACTION_INFORMATION_CLIENT: true
#Do you want to show "Somebody bought/sold... " messages?
SHOW_TRANSACTION_INFORMATION_OWNER: true

#If true, plugin will log transactions in its own file
LOG_TO_FILE: false
#Do you want ChestShop's messages to show up in console?
LOG_TO_CONSOLE: true
#Should all shop removals be logged to the console?
LOG_ALL_SHOP_REMOVALS: true

#Do you want to stack all items up to 64 item stacks?
STACK_TO_64: false
#Do you want to use built-in protection against chest destruction?
USE_BUILT_IN_PROTECTION: true
#Do you want to have shop signs "stick" to chests?
STICK_SIGNS_TO_CHESTS: false
#EXPERIMENTAL: Do you want to turn off the default protection when another plugin is protecting the block? (Will leave the chest visually open - CraftBukkit bug!)
TURN_OFF_DEFAULT_PROTECTION_WHEN_PROTECTED_EXTERNALLY: false
#Do you want to turn off the default sign protection? Warning! Other players will be able to destroy other people's shops!
TURN_OFF_SIGN_PROTECTION: false
#Do you want to disable the hopper protection, which prevents Hopper-Minecarts from taking items out of shops?
TURN_OFF_HOPPER_PROTECTION: false
#Do you want to protect shop chests with LWC?
PROTECT_CHEST_WITH_LWC: false
#Of which type should the container protection be? Possible type: public, private, donate and on some LWC versions display
LWC_CHEST_PROTECTION_TYPE: "PRIVATE"
#Do you want to protect shop signs with LWC?
PROTECT_SIGN_WITH_LWC: false
#Of which type should the sign protection be? Possible type: public, private, donate and on some LWC versions display
LWC_SIGN_PROTECTION_TYPE: "PRIVATE"
#Should the chest's LWC protection be removed once the shop sign is destroyed? 
REMOVE_LWC_PROTECTION_AUTOMATICALLY: true

#Do you want to only let people build inside WorldGuard regions?
WORLDGUARD_INTEGRATION: false
#Do you want to only let people build inside region flagged by doing /region regionName flag allow-shop allow?
WORLDGUARD_USE_FLAG: false
#Do you want ChestShop to respect WorldGuard's chest protection?
WORLDGUARD_USE_PROTECTION: false

#Do you want to only let people build inside GriefPrevention claims?
GRIEFPREVENTION_INTEGRATION: false

#Do you want to only let people build inside RedProtect regions?
REDPROTECT_INTEGRATION: false

#Do you want to deny shop access to unlogged users?
AUTHME_HOOK: true
#Do you want to allow shop access to unregistered users? (Example: registration is optional)
AUTHME_ALLOW_UNREGISTERED: false

#How much Heroes exp should people get for creating a ChestShop?
HEROES_EXP: 100.0

#Add icons and make item names hoverable in transaction messages when ShowItem is installed?
SHOWITEM_MESSAGE: true

# Should the plugin log some messages that are useful for debugging?
DEBUG: false
# Do you want to turn off the automatic notifications for new development builds?
TURN_OFF_DEV_UPDATE_NOTIFIER: false
# Do you want to include some values of this config in the metrics? (This will not leak sensitive data but help in the development process)
INCLUDE_SETTINGS_IN_METRICS: true

# The default language when the client's language can't be found.
DEFAULT_LANGUAGE: "en"
# Should the plugin try to use a language file that matches the client's locale setting?
USE_CLIENT_LOCALE: true
# If true, people will be able to sell/buy everything available of the same type.
SHIFT_SELLS_EVERYTHING: true
# The uuid of the economy account for the Admin Shop. Useful for fake accounts as normally only accounts of players work
SERVER_ECONOMY_ACCOUNT_UUID: 00000000-0000-0000-0000-000000000000

# Maximum amount of items that can be bought/sold at a shop. Default 3456 is a double chest of 64 stacks.
MAX_SHOP_AMOUNT: 3456
# Only allow users to buy/sell that have access to the sign's protection? (E.g. LWC protection)
CHECK_ACCESS_FOR_SHOP_USE: false
# Should LWC limits block shop creations?
LWC_LIMITS_BLOCK_CREATION: true

# If true and in 1.14+, the owner of a chest shop can click with a dye / ink sac to dye the sign.
SIGN_DYING: true
# Make all admin shops be unlimited even if they have a shop container at the sign
FORCE_UNLIMITED_ADMIN_SHOP: false
# This makes sure that the UUIDs of player shop accounts match the server's online-mode setting. Disabling this might lead to issues with offline players and is therefore unsupported!
ENSURE_CORRECT_PLAYERID: false
# This regexp validates the name of the player. If the name doesn't match, the player will neither be able to create a valid shop sign, nor buy/sell from a shop.
# Note for Bedrock support: If you have Floodgate on your server, you should set this regexp to ^\\*?\\w+$ and ENSURE_CORRECT_PLAYERID to false
# If your Floodgate prefix is not *, change the first * in the regexp (the one before the question mark) to whatever your prefix is.
VALID_PLAYERNAME_REGEXP: "^\\w+$"

# Add stock counter to quantity line?
USE_STOCK_COUNTER: false
 ```

</details>

### Server Version

git-Paper-66 (MC:1.18)

### Server Log

<details>
  <summary>Log</summary>

  ```
[04:35:14 INFO]: [ChestShop] +Rockethub created a shop - 1 Stone - B 1 - at [world] 6426, 90, -6101
  ```

</details>

### What other plugins are you running?

Plugins (81): AdvancedPortals (0.5.6), AlwaysInfect (1.0), AntiSeedCracker (1.0), AuctionHouse (3.1), BedrockPlayerManager (1.4), BetterGUI (4.0), BetterRTP (3.2.1-4), boosCooldowns (3.17.1), BungeeTabListPlus (3.4.0), BuycraftX (12.0.8), Celeste (1.51), ChestShop (3.12.1-SNAPSHOT (compiled at 2021-12-22T09:14:00Z)), ChestShop-LegacyIds (1.0-SNAPSHOT (build 54)), ChestShopNotifier (1.2.1-SNAPSHOT (build #23)), Citizens (2.0.29-SNAPSHOT (build 2419)), CMILib (1.1.0.3), CombatLogX (10.4.2.4), CommandNPC (1.9.1), CoreProtect (20.2), CustomCrafting (1.7.1.3), DisableJoinQuitMsg (1.1), DiscordSRV (1.24.0), Essentials (2.19.2), EssentialsChat (2.19.2), EssentialsSpawn (2.19.2), floodgate (2.1.0-SNAPSHOT), Freeze (2.2.2), GalacticFly (1.0.53), GalacticUpdater (1.0.20), GoldenCrates (3.11.0), GSit ([6.0.4.1]), HamsterAPI (0.1.8), HeadDB (2.4.4), HolographicDisplays (3.0.0-SNAPSHOT), InfiniteVouchers (2.3.1), InteractiveBoard (15.3), InventoryRollbackPlus (1.6.5), IPWhitelist (1.7), ItemEdit (2.18), Jobs (5.0.1.0), LagAssist (2.27.0), LaunchPads (1.2), LiteBans (2.7.5), LitePlaytimeRewards (2.4.8), Lottery (1.4.5), LuckPerms (5.3.47), LWC (2.1.5-09ad392), mcMMO (1.6.5), mcMMOAction (2.4-SNAPSHOT), MovingDevApi (1.1.10), MyCommand (5.7.1), NamelessMC (2.1.1), NametagEdit (4.5.4), NexEngine (2.0.7.4), OldCombatMechanics (1.10.0), OpenInv (4.1.9), PartyChatSpy (1.0.0), PlaceholderAPI (2.10.10), PlayerVaults (4.1.17), PluginConstructorAPI (1.0.52), PlugManX (2.2.7), PremiumVanish (2.7.8), ProtocolLib (4.8.0-SNAPSHOT-b538), RampenDrills (4.5.2-Beta), Residence (5.0.1.0), Shopkeepers (2.14.0-SNAPSHOT+02f69430), SirBlobmanCore (2.3.4), Spartan (Build 440.1), UltimateAutoRestart (Build 48a), Vault (1.7.3-b131), ViaBackwards (4.1.1), ViaRewind (2.0.1), ViaVersion (4.1.1), Votifier (2.7.3), Voting (2.6.0), VotingPlugin (6.7.1), WolfyUtilities (1.8.0.0), WorldEdit (7.2.8+6008-1246d61), WorldEditSUI (1.7.2), WorldGuard (7.0.7-SNAPSHOT+2165-81750e1), SilkSpawners (7.1.0)

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)
