### ISSUE TITLE
`ItemMoveListener` causing a lot of lag due to `isShopBlock` creating chest snapshots

### ISSUE THREAD

**Issue by MrPowerGamerBR** [ChestShop-authors/ChestShop-3#604]
### What is happening?

ChestShop is using a LOT of CPU time due to the snapshots created for the `isShopBlock` checks. While ChestShop does take care to not create snapshots on the `ItemMoveListener` for the source/destination blocks, ChestShop still checks chests with snapshots, which causes the TPS to tank hard if you have multiple hoppers.

Currently the `isShopBlock` implementation is like this...
```java
    public static boolean isShopBlock(InventoryHolder holder) {
        if (holder instanceof DoubleChest) {
            return isShopBlock(((DoubleChest) holder).getLeftSide())
                    || isShopBlock(((DoubleChest) holder).getRightSide());
        } else if (holder instanceof BlockState) {
            return isShopBlock(((BlockState) holder).getBlock());
        }
        return false;
    }
```

But it could be like this, considering that it seems that ChestShop doesn't need the block states to be a snapshot.
```java
    public static boolean isShopBlock(InventoryHolder holder) {
        if (holder instanceof DoubleChest) {
            return isShopBlock(ImplementationAdapter.getLeftSide((DoubleChest) holder, false))
                    || isShopBlock(ImplementationAdapter.getRightSide((DoubleChest) holder, false));
        } else if (holder instanceof BlockState) {
            return isShopBlock(((BlockState) holder).getBlock());
        }
        return false;
    }
```

Currently as a workaround I'm using `TURN_OFF_HOPPER_PROTECTION` to true, that "fixes" the issue.

![image](https://github.com/user-attachments/assets/797ba233-c45c-4555-8923-2102928314bc)

![image](https://github.com/user-attachments/assets/ba22ec93-1cb4-4782-a955-85db2a94f883)

### What did you expect to happen?

For ChestShop to not lag xd

### Plugin Version

ChestShop version 3.12.3-SNAPSHOT (build 417)

### Plugin Config

```yml
TURN_OFF_UPDATES: false
#Do you want to turn off the automatic updates of ChestShop?

CACHE_SIZE: 1000
#How large should the internal uuid and name caches be?

SHOP_INTERACTION_INTERVAL: 250
#(In 1/1000th of a second) How often can a player use the shop sign?
IGNORE_CREATIVE_MODE: true
#Do you want to allow using shops to people in creative mode?
REVERSE_BUTTONS: false
#If true, people will buy with left-click and sell with right-click.
SHIFT_SELLS_IN_STACKS: true
#If true, people will be able to buy/sell in 64 stacks while holding the crouch button.
SHIFT_ALLOWS: "ALL"
#What can you do by clicking shift with SHIFT_SELLS_IN_STACKS turned on? (ALL/BUY/SELL)
ALLOW_SIGN_CHEST_OPEN: false
#Can shop's chest be opened by owner with right-clicking a shop's sign?
ALLOW_LEFT_CLICK_DESTROYING: true
#If true, when you left-click your own shop sign you won't open chest's inventory, but instead you will start destroying the sign.

REMOVE_EMPTY_SHOPS: false
#If true, if the shop is empty, the sign is destroyed and put into the chest, so the shop isn't usable anymore.
REMOVE_EMPTY_CHESTS: false
#If true, if the REMOVE_EMPTY_SHOPS option is turned on, the chest is also destroyed.

ADMIN_SHOP_NAME: "SparklyShop"
#First line of your Admin Shop's sign should look like this:
SERVER_ECONOMY_ACCOUNT: ""
#The economy account which Admin Shops should use and to which all taxes will go
TAX_AMOUNT: 0
#Percent of the price that should go to the server's account. (100 = 100 percent)
SERVER_TAX_AMOUNT: 0
#Percent of the price that should go to the server's account when buying from an Admin Shop.
SHOP_CREATION_PRICE: 0.0
#Amount of money player must pay to create a shop
SHOP_REFUND_PRICE: 0.0
#How much money do you get back when destroying a sign?

BLOCK_SHOPS_WITH_SELL_PRICE_HIGHER_THAN_BUY_PRICE: true
#Should we block shops that sell things for more than they buy? (This prevents newbies from creating shops that would be exploited)

ALLOW_MULTIPLE_SHOPS_AT_ONE_BLOCK: true
#Do you want to allow other players to build a shop on a block where there's one already?
ALLOW_PARTIAL_TRANSACTIONS: true
#Can shops be used even when the seller doesn't have enough items? (The price will be scaled adequately to the item amount)
ALLOW_AUTO_ITEM_FILL: true
#Can '?' be put in place of item name in order for the sign to be auto-filled?

SHOW_MESSAGE_OUT_OF_STOCK: true
#Do you want to show "Out of stock" messages?
SHOW_MESSAGE_FULL_SHOP: true
#Do you want to show "Full shop" messages?

CSTOGGLE_TOGGLES_OUT_OF_STOCK: false
#Can players hide the "Out of stock" messages with /cstoggle?
CSTOGGLE_TOGGLES_FULL_SHOP: false
#Can players hide the "Full shop" messages with /cstoggle?
SHOW_TRANSACTION_INFORMATION_CLIENT: true
#Do you want to show "You bought/sold... " messages?
SHOW_TRANSACTION_INFORMATION_OWNER: true
#Do you want to show "Somebody bought/sold... " messages?

LOG_TO_FILE: true
#If true, plugin will log transactions in its own file
LOG_TO_CONSOLE: true
#Do you want ChestShop's messages to show up in console?

STACK_TO_64: false
#Do you want to stack all items up to 64 item stacks?
USE_BUILT_IN_PROTECTION: true
#Do you want to use built-in protection against chest destruction?
STICK_SIGNS_TO_CHESTS: false
#Do you want to have shop signs "stick" to chests?
TURN_OFF_DEFAULT_PROTECTION_WHEN_PROTECTED_EXTERNALLY: false
#EXPERIMENTAL: Do you want to turn off the default protection when another plugin is protecting the block? (Will leave the chest visually open - CraftBukkit bug!)
TURN_OFF_SIGN_PROTECTION: false
#Do you want to turn off the default sign protection? Warning! Other players will be able to destroy other people's shops!
TURN_OFF_HOPPER_PROTECTION: false
#Do you want to disable the hopper protection, which prevents the hoppers from taking items out of chests?
PROTECT_CHEST_WITH_LWC: false
#Do you want to protect shop chests with LWC?
PROTECT_SIGN_WITH_LWC: false
#Do you want to protect shop signs with LWC?
REMOVE_LWC_PROTECTION_AUTOMATICALLY: true
#Should the chest's LWC protection be removed once the shop sign is destroyed? 

WORLDGUARD_INTEGRATION: false
#Do you want to only let people build inside regions?
WORLDGUARD_USE_FLAG: true
#Do you want to only let people build inside region flagged by doing /region regionName flag allow-shop allow?
WORLDGUARD_USE_PROTECTION: false
#Do you want ChestShop to respect WorldGuard's chest protection?

AUTHME_HOOK: true
#Do you want to deny shop access to unlogged users?
AUTHME_ALLOW_UNREGISTERED: false
#Do you want to allow shop access to unregistered users? (Example: registration is optional)

HEROES_EXP: 100.0
#How much Heroes exp should people get for creating a ChestShop?

#A list of worlds in which to remove empty shops with the previous config. Case sensitive. An empty list means all worlds.
REMOVE_EMPTY_WORLDS: 
- "world1"
- "world2"
#How many decimal places are allowed at a maximum for prices?
PRICE_PRECISION: 2

#Add icons and make item names hoverable in transaction messages when ShowItem is installed?
SHOWITEM_MESSAGE: true


#What containers are allowed to hold a shop? (Only blocks with inventories work!)
SHOP_CONTAINERS: 
- "CHEST"
- "TRAPPED_CHEST"
- "BARREL"
#Do you want to allow using shops to people who have access to it due to their permissions? (owners are always ignored)
IGNORE_ACCESS_PERMS: false

#How many seconds do you want to wait before showing notifications for the same shop to the owner again?
NOTIFICATION_MESSAGE_COOLDOWN: 10
#Should all shop removals be logged to the console?
LOG_ALL_SHOP_REMOVALS: true


#Enable this if you use BungeeCord and want players to receive shop notifications on other servers
BUNGEECORD_MESSAGES: false

#Of which type should the container protection be? Possible type: public, private, donate and on some LWC versions display
LWC_CHEST_PROTECTION_TYPE: "PRIVATE"
#Of which type should the sign protection be? Possible type: public, private, donate and on some LWC versions display
LWC_SIGN_PROTECTION_TYPE: "PRIVATE"

#Do you want to only let people build inside GriefPrevention claims?
GRIEFPREVENTION_INTEGRATION: false

#Do you want to only let people build inside RedProtect regions?
REDPROTECT_INTEGRATION: false

# Should the plugin log some messages that are useful for debugging?
DEBUG: false
# If true, people will be able to sell/buy everything available of the same type.
SHIFT_SELLS_EVERYTHING: false
# The uuid of the economy account for the Admin Shop. Useful for fake accounts as normally only accounts of players work
SERVER_ECONOMY_ACCOUNT_UUID: 00000000-0000-0000-0000-000000000000

# Maximum amount of items that can be bought/sold at a shop. Default 3456 is a double chest of 64 stacks.
MAX_SHOP_AMOUNT: 3456
# Should LWC limits block shop creations?
LWC_LIMITS_BLOCK_CREATION: true

# Do you want to turn off the automatic notifications for new development builds?
TURN_OFF_DEV_UPDATE_NOTIFIER: false
# Do you want to include some values of this config in the metrics? (This will not leak sensitive data but help in the development process)
INCLUDE_SETTINGS_IN_METRICS: true

# The default language when the client's language can't be found.
DEFAULT_LANGUAGE: "pt_BR"
# Should the plugin try to use a language file that matches the client's locale setting?
USE_CLIENT_LOCALE: false
# If true and in 1.14+, the owner of a chest shop can click with a dye / ink sac to dye the sign.
SIGN_DYING: true
# Make all admin shops be unlimited even if they have a shop container at the sign
FORCE_UNLIMITED_ADMIN_SHOP: false
# This makes sure that the UUIDs of player shop accounts match the server's online-mode setting. Disabling this might lead to issues with offline players and is therefore unsupported!
ENSURE_CORRECT_PLAYERID: true
# This regexp validates the name of the player. If the name doesn't match, the player will neither be able to create a valid shop sign, nor buy/sell from a shop.
# Note for Bedrock support: If you have Floodgate on your server, you should set this regexp to ^\\*?\\w+$ and ENSURE_CORRECT_PLAYERID to false
# If your Floodgate prefix is not *, change the first * in the regexp (the one before the question mark) to whatever your prefix is.
VALID_PLAYERNAME_REGEXP: "^\\w+$"
# Only allow users to buy/sell that have access to the sign's protection? (E.g. LWC protection)
CHECK_ACCESS_FOR_SHOP_USE: false

# Add stock counter to quantity line?
USE_STOCK_COUNTER: false

# Do you want to turn off the automatic notifications for releases?
TURN_OFF_UPDATE_NOTIFIER: false
# Should the plugin strip the colors from formatted price?
STRIP_PRICE_COLORS: false
```

### Server Version

`This server is running SparklyPaper version 1.20.6-DEV-ver/1.20.6@099860a (2024-06-30T03:31:05Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)`

### Server Log

*there isn't any errors*

### What other plugins are you running?

```
[04:34:03 INFO]: Server Plugins (105):
[04:34:03 INFO]: Bukkit Plugins:
[04:34:03 INFO]:  - ChestShop, Citizens, CoreProtect, DreamAjuda, DreamAntiAFK, DreamArmorStandEditor, DreamAssinaturas, DreamAuth, DreamBedrockIntegrations, DreamBlockParty
[04:34:03 INFO]:  DreamBlockVIPItems, DreamBrisa, DreamBroadcast, DreamBusca, DreamCaixaSecreta, DreamCasamentos, DreamCash, DreamCassino, DreamChat, DreamChatTags
[04:34:03 INFO]:  DreamChestShopStuff, DreamClubes, DreamColorEmote, DreamCore, DreamCorreios, DreamCorrida, DreamCustomItems, DreamDemocracy, DreamDiscordCommandRelayer, DreamElevador
[04:34:03 INFO]:  DreamEmptyWorldGenerator, DreamEnchant, DreamEnderHopper, DreamEquipCoolStuff, DreamEsponjas, DreamFight, DreamFusca, DreamHeads, DreamHome, DreamJetpack
[04:34:03 INFO]:  DreamKits, DreamLabirinto, DreamLagStuffRestrictor, DreamLobbyFun, DreamLoja, DreamMapWatermarker, DreamMcMMOFun, DreamMinaRecheada, DreamMini, DreamMobSpawner
[04:34:03 INFO]:  DreamMochilas, DreamMoverSpawners, DreamMusically, DreamPicaretaMonstra, DreamPrivada, DreamPvPTweaks, DreamQuickHarvest, DreamQuiz, DreamRaffle, DreamRaspadinha
[04:34:03 INFO]:  DreamReparar, DreamResourcePack, DreamResourceReset, DreamRestarter, DreamRoadProtector, DreamScoreboard, DreamSeamlessWorlds, DreamShopHeads, DreamSocial, DreamSonecas
[04:34:03 INFO]:  DreamTerrainAdditions, DreamTNTRun, DreamTorreDaMorte, DreamTrails, DreamTreeAssist, DreamVanish, DreamVIPStuff, DreamVote, DreamWarps, DreamXizum
[04:34:03 INFO]:  dynmap, EntityDetection, ExtraContexts, GriefPrevention, GSit, HolographicDisplays, LangUtils, LuckPerms, mcMMO, Multiverse-Core
[04:34:03 INFO]:  NoCheatPlus, NoteBlockAPI, OldCombatMechanics, PlayerStatueBuilderX, PlugManX, ProtocolLib, spark, SparklyDreamer, Vault, ViaBackwards
[04:34:03 INFO]:  ViaVersion, Votifier, WorldBorder, WorldEdit, WorldGuard
```

### Agreements

- [X] I have checked if there are already similar issues open.
- [X] I am running the latest development version available from https://ci.minebench.de/job/ChestShop-3/.
- [X] The version [has support](https://github.com/ChestShop-authors/ChestShop-3/security/policy#supported-versions) for this type of issue.
- [X] I have provided all requested information and agree to the terms of the [project's license](https://github.com/ChestShop-authors/ChestShop-3/blob/master/LICENSE)

### Additional context

Yes, in reality I'm not running the latest version (it is a few builds behind), but I have checked the code and there wasn't any changes on that code path between the version I'm using and the latest version.

And yes, I'm using a Paper fork that I made, but by looking at the code I can see that the same behavior would also happen in Paper.
